# Generated by Django 5.0 on 2025-01-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', 'create_music_tastes'),
    ]

    operations = [
        migrations.AddField(
            model_name='musictaste',
            name='spotify_genres',
            field=models.JSONField(default=list),
        ),
    ]
