# Generated by Django 5.0 on 2025-01-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', 'create_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicpost',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='musicpost',
            name='youtube_link',
        ),
        migrations.AddField(
            model_name='musicpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AddField(
            model_name='musicpost',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='musicpost',
            name='mood',
            field=models.CharField(blank=True, choices=[('morning', '朝'), ('night', '夜'), ('rain', '雨の日'), ('drive', 'ドライブ'), ('work', '作業'), ('relax', 'リラックス'), ('party', 'パーティー')], max_length=20),
        ),
        migrations.AddField(
            model_name='musicpost',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='musicpost',
            name='artist',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='musicpost',
            name='spotify_link',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='musicpost',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
