# Generated by Django 5.0 on 2025-01-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', 'remove_profile_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_artists',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
