# Generated by Django 5.0 on 2025-01-15 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_remove_musicpost_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicpost',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
