# Generated by Django 5.0 on 2025-01-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_musictaste_spotify_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='musictaste',
            name='favorite_artists',
            field=models.JSONField(default=dict),
        ),
    ]
