# Generated by Django 5.0 on 2025-01-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_musictaste_favorite_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musictaste',
            name='favorite_artists',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='musictaste',
            name='genres',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='musictaste',
            name='moods',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='musictaste',
            name='spotify_genres',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
