# Generated by Django 5.0 on 2025-01-16 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_musicpost_analysis_points_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='post',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='storyview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='storyview',
            name='story',
        ),
        migrations.RemoveField(
            model_name='storyview',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='musicstory',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Music stories'},
        ),
        migrations.RemoveField(
            model_name='musicpost',
            name='listening_context',
        ),
        migrations.RemoveField(
            model_name='musicpost',
            name='location',
        ),
        migrations.RemoveField(
            model_name='musicpost',
            name='recommended_for',
        ),
        migrations.RemoveField(
            model_name='musicpost',
            name='related_artists',
        ),
        migrations.RemoveField(
            model_name='musicpost',
            name='scheduled_time',
        ),
        migrations.RemoveField(
            model_name='musicstory',
            name='album_art',
        ),
        migrations.RemoveField(
            model_name='musicstory',
            name='mood_emoji',
        ),
        migrations.RemoveField(
            model_name='musicstory',
            name='preview_url',
        ),
        migrations.RemoveField(
            model_name='musicstory',
            name='reaction_count',
        ),
        migrations.RemoveField(
            model_name='musicstory',
            name='spotify_track_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='music_mood_preferences',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='musicpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='musicstory',
            name='spotify_link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musicstory',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='viewed_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='musicpost',
            name='analysis_points',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='musicpost',
            name='artist',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='musicpost',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='musicpost',
            name='lyrics_excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='musicpost',
            name='music_elements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='musicpost',
            name='post_type',
            field=models.CharField(choices=[('review', 'レビュー'), ('analysis', '楽曲分析'), ('memory', '思い出'), ('recommendation', 'おすすめ'), ('playlist', 'プレイリスト紹介')], default='review', max_length=20),
        ),
        migrations.AlterField(
            model_name='musicpost',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='musicpost',
            name='spotify_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='musicpost',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='musicpost',
            name='youtube_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='musicstory',
            name='artist',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='musicstory',
            name='background_theme',
            field=models.CharField(choices=[('default', 'デフォルト'), ('wave', '波形'), ('stars', '星空'), ('gradient', 'グラデーション'), ('vinyl', 'レコード')], default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='musicstory',
            name='comment',
            field=models.TextField(blank=True, default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='musicstory',
            name='listening_status',
            field=models.CharField(choices=[('now_playing', '今聴いている'), ('just_discovered', '発見した'), ('recommendation', 'おすすめ'), ('memory', '思い出の一曲')], max_length=20),
        ),
        migrations.AlterField(
            model_name='musicstory',
            name='mood',
            field=models.CharField(choices=[('happy', 'ハッピー'), ('chill', 'リラックス'), ('energetic', 'エネルギッシュ'), ('sad', 'メランコリー'), ('love', 'ラブ')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='musicstory',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='musicstory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_artists',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_genres',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='profile',
            name='spotify_refresh_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MusicTaste',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.DeleteModel(
            name='StoryView',
        ),
    ]
