# Generated by Django 5.0 on 2025-01-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_profile_followers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musictaste',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='musictaste',
            name='spotify_genres',
        ),
        migrations.RemoveField(
            model_name='musictaste',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='musictaste',
            name='favorite_artists',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='musictaste',
            name='genres',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='musictaste',
            name='moods',
            field=models.JSONField(default=dict),
        ),
    ]
