# Generated by Django 5.0 on 2025-01-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_musictaste_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musictaste',
            name='favorite_artists',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='musictaste',
            name='genres',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='musictaste',
            name='moods',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
