# Generated by Django 5.0 on 2025-01-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_musictaste_favorite_artists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicstory',
            name='album_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='musicstory',
            name='artist_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='musicstory',
            name='track_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
