# Generated by Django 5.0 on 2025-01-17 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_musicstory_album_image_url_musicstory_artist_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicpost',
            name='analysis_points',
        ),
        migrations.RemoveField(
            model_name='musicpost',
            name='listening_context',
        ),
        migrations.RemoveField(
            model_name='musicpost',
            name='location',
        ),
        migrations.RemoveField(
            model_name='musicpost',
            name='lyrics_excerpt',
        ),
        migrations.RemoveField(
            model_name='musicpost',
            name='music_elements',
        ),
        migrations.RemoveField(
            model_name='musicpost',
            name='post_type',
        ),
        migrations.RemoveField(
            model_name='musicpost',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='musicpost',
            name='recommended_for',
        ),
        migrations.RemoveField(
            model_name='musicpost',
            name='related_artists',
        ),
        migrations.RemoveField(
            model_name='musicpost',
            name='scheduled_time',
        ),
        migrations.RemoveField(
            model_name='musicpost',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='musicpost',
            name='youtube_link',
        ),
        migrations.AddField(
            model_name='musicpost',
            name='is_playlist_track',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='musicpost',
            name='artist',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='musicpost',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='musicpost',
            name='mood',
            field=models.CharField(blank=True, choices=[('happy', '楽しい'), ('sad', '悲しい'), ('excited', 'テンション高め'), ('relaxed', 'リラックス'), ('energetic', 'エネルギッシュ'), ('calm', '穏やか'), ('romantic', 'ロマンティック'), ('nostalgic', 'ノスタルジック')], max_length=50),
        ),
        migrations.AlterField(
            model_name='musicpost',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='musicpost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
