# Generated by Django 3.2.25 on 2025-01-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_profile_music_taste_alter_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicpost',
            name='mood',
        ),
        migrations.AddField(
            model_name='musicpost',
            name='post_type',
            field=models.CharField(choices=[('lyrics_analysis', '歌詞考察'), ('impression', '感想共有')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
