# Generated by Django 3.2.25 on 2025-01-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20250122_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicpost',
            name='post_type',
            field=models.CharField(choices=[('lyrics_analysis', '歌詞考察'), ('impression', '感想共有'), ('memory', '思い出共有')], max_length=50),
        ),
    ]
