# Generated by Django 3.2.25 on 2025-01-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_musicpost_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicpost',
            name='album_artist',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='musicpost',
            name='album_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='musicpost',
            name='artist_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='musicpost',
            name='spotify_album_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='musicpost',
            name='spotify_artist_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='musicpost',
            name='spotify_track_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='musicpost',
            name='target_type',
            field=models.CharField(choices=[('track', '曲について'), ('artist', 'アーティストについて'), ('album', 'アルバムについて')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='musicpost',
            name='artist',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='musicpost',
            name='post_type',
            field=models.CharField(choices=[('lyrics_analysis', '歌詞考察'), ('track_impression', '感想共有'), ('track_memory', '思い出共有'), ('artist_introduction', 'アーティスト紹介'), ('artist_impression', '感想共有'), ('artist_memory', '思い出共有'), ('album_review', 'アルバムレビュー'), ('album_impression', '感想共有'), ('album_memory', '思い出共有')], max_length=50),
        ),
        migrations.AlterField(
            model_name='musicpost',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
